Branch2
MartinPetrakiev/c_sharp_multidymentional_arrays pull request #2
Opened 2023-08-22 08:40 UTC by MartinPetrakiev

2023-08-30 19:26 UTC, mvlt requested changes
refactoring needed and finish for D

2023-08-30 19:26 UTC, mvlt commented on Fill_the_matrix/Program.cs
> +            if (type == "a")
Better switch case when so much options

2023-08-30 19:26 UTC, mvlt commented on Fill_the_matrix/Program.cs
> +        static void FillPatternA(int[,] matrix, int n)
No need of second param in all functions

2023-08-30 19:26 UTC, mvlt commented on Fill_the_matrix/Program.cs
> +            }
What if you get "e"

2023-08-30 19:27 UTC, mvlt requested changes
No description

2023-08-30 19:32 UTC, mvlt commented on Maximal_sum/Program.cs
> +        CalculateMaxSumOf3x3(matrix, n, m);
No need of last two params

2023-08-30 19:39 UTC, mvlt commented on Binary_search/Program.cs
> +            Console.WriteLine(array[~indexK - 1]);
What will happen if ~indexK equals 0?

2023-08-30 19:41 UTC, mvlt requested changes
All scenarios should to be handled

2023-08-30 19:44 UTC, mvlt requested changes
Check what is doing the second parameter passed to Array.Sort build in function

2023-08-31 08:56 UTC, MartinPetrakiev commented on Fill_the_matrix/Program.cs
> +            if (type == "a")
Fill_the_matrix solution was not published. This was the initial commit.
code refactoring of iunitial in commit
[76c6369](https://github.com/MartinPetrakiev/c_sharp_multidymentional_arrays/pull/2/commits/76c6369e528a67abebfc26807c6180a7974ef554)
Includes swtich case.

2023-08-31 08:58 UTC, MartinPetrakiev commented on Binary_search/Program.cs
> +            Console.WriteLine(array[~indexK - 1]);
scenario handled at commit
[32b0db4](https://github.com/MartinPetrakiev/c_sharp_multidymentional_arrays/pull/2/commits/32b0db467428387e267a685726b06f851306cb32)

2023-10-16 14:30 UTC, merged